# Generated by Django 6.0.1 on 2026-01-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_status_booking_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('09:00-10:00', '09:00 – 10:00'), ('10:00-11:00', '10:00 – 11:00'), ('11:00-12:00', '11:00 – 12:00'), ('14:00-15:00', '14:00 – 15:00')], default='09:00AM', max_length=20),
        ),
    ]
