# Generated by Django 6.0.1 on 2026-01-22 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_time_slot'),
        ('users', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('09:00-10:00', '09:00 – 10:00'), ('10:00-11:00', '10:00 – 11:00'), ('11:00-12:00', '11:00 – 12:00'), ('14:00-15:00', '14:00 – 15:00')], default='09:00-10:00', max_length=20),
        ),
    ]
