# Generated by Django 6.0.1 on 2026-01-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_paid_alter_booking_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('09:00-10:00', '09:00 – 10:00'), ('10:00-11:00', '10:00 – 11:00'), ('11:00-12:00', '11:00 – 12:00'), ('14:00-15:00', '14:00 – 15:00')], max_length=20),
        ),
    ]
