# Generated by Django 6.0.1 on 2026-01-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_paid_booking_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('IN_PERSON', 'Pay in person')], default='UNPAID', max_length=20),
        ),
    ]
