# Generated by Django 6.0.1 on 2026-02-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lesson_type',
            field=models.CharField(choices=[('FREE', 'Free Intro (15 mins)'), ('45', '45 Minutes'), ('60', '60 Minutes'), ('90', '90 Minutes')], default='60', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
